use std::{
    collections::HashSet,
    collections::VecDeque,
    env,
    error::Error,
    fs::File,
    io::{BufRead, BufReader},
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SpaceType {
    Empty,
    Beam,
    Splitter,
}

#[derive(Debug, Clone, Copy, Hash, PartialEq, Eq)]
pub struct CartesianCoordinate {
    pub x: usize,
    pub y: usize,
}

type SpaceMeta = (CartesianCoordinate, SpaceType);
type ProblemMeta = (Vec<SpaceMeta>, Vec<SpaceMeta>, usize, usize);

fn calculate_total_beams(
    beams: Vec<SpaceMeta>,
    splitters: Vec<SpaceMeta>,
    width: usize,
    height: usize,
) -> u32 {
    let mut queue: VecDeque<CartesianCoordinate> =
        beams.into_iter().map(|(coord, _)| coord).collect();

    let splitter_coords: HashSet<CartesianCoordinate> =
        splitters.into_iter().map(|(coord, _)| coord).collect();

    let mut seen: HashSet<CartesianCoordinate> = HashSet::new();

    let mut total = 0;

    while let Some(coord) = queue.pop_front() {
        let next_row = coord.x + 1;
        if next_row >= height {
            continue;
        }

        let next = CartesianCoordinate {
            x: next_row,
            y: coord.y,
        };

        if !seen.insert(next) {
            continue;
        }

        if splitter_coords.contains(&next) {
            total += 1;
            if coord.y > 0 {
                queue.push_back(CartesianCoordinate {
                    x: next.x,
                    y: next.y - 1,
                });
            }

            if coord.y < width - 1 {
                queue.push_back(CartesianCoordinate {
                    x: next.x,
                    y: next.y + 1,
                });
            }
        } else {
            queue.push_back(next);
        }
    }
    total
}

fn char_to_space_type(c: &char) -> SpaceType {
    match c {
        '.' => SpaceType::Empty,
        'S' | '|' => SpaceType::Beam,
        '^' => SpaceType::Splitter,
        _ => SpaceType::Empty,
    }
}

fn read_file(file_path: &str) -> Result<ProblemMeta, Box<dyn Error>> {
    let h_file = File::open(file_path)?;
    let reader = BufReader::new(h_file);
    let lines: Vec<String> = reader.lines().collect::<Result<Vec<_>, _>>()?;

    let height = lines.len();
    let width = lines.first().map(|s| s.len()).unwrap_or(0);

    let meta_data: Vec<SpaceMeta> = lines
        .iter()
        .enumerate()
        .flat_map(|(line_idx, line)| {
            line.chars().enumerate().map(move |(char_idx, char)| {
                (
                    CartesianCoordinate {
                        x: line_idx,
                        y: char_idx,
                    },
                    char_to_space_type(&char),
                )
            })
        })
        .collect();

    let beams: Vec<SpaceMeta> = meta_data
        .iter()
        .copied()
        .filter(|(_, space_type)| *space_type == SpaceType::Beam)
        .collect();

    let splitters: Vec<SpaceMeta> = meta_data
        .iter()
        .copied()
        .filter(|(_, space_type)| *space_type == SpaceType::Splitter)
        .collect();

    Ok((beams, splitters, width, height))
}

fn main() -> Result<(), Box<dyn Error>> {
    let path = env::args().nth(1).expect("usage: aoc7pt1 <input-file>");
    let (beams, splitters, width, height): ProblemMeta = read_file(&path)?;
    let total = calculate_total_beams(beams, splitters, width, height);
    println!("final = {total}");
    Ok(())
}

/*
--- Day 7: Laboratories ---

You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.

Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.

Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.

Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

For example:

.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

.......S.......
.......|.......
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

At that point, the original beam stops, and two new beams are emitted from the splitter:

.......S.......
.......|.......
......|^|......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

Those beams continue downward until they reach more splitters:

.......S.......
.......|.......
......|^|......
......|.|......
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............

This process continues until all of the tachyon beams reach a splitter or exit the manifold:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|

To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

Analyze your manifold diagram. How many times will the beam be split?
*/
